// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/what-is-xavyo',
        'getting-started/key-concepts',
        'getting-started/quick-tour',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Admin',
          items: [
            'guides/admin/tenant-setup',
            'guides/admin/user-management',
            'guides/admin/authentication',
            'guides/admin/authorization',
            'guides/admin/connectors',
            'guides/admin/governance',
            'guides/admin/security-hardening',
            'guides/admin/nhi-management',
          ],
        },
        {
          type: 'category',
          label: 'Developer',
          items: [
            'guides/developer/api-overview',
            'guides/developer/authentication-flows',
            'guides/developer/scim-integration',
            'guides/developer/webhooks',
            'guides/developer/nhi-machine-identities',
          ],
        },
        {
          type: 'category',
          label: 'End User',
          items: [
            'guides/end-user/self-service',
            'guides/end-user/mfa-setup',
            'guides/end-user/access-requests',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/identity-governance',
        'concepts/zero-trust',
        'concepts/multi-tenancy',
        'concepts/lifecycle-management',
        'concepts/separation-of-duties',
        'concepts/non-human-identities',
        'concepts/compliance-gdpr',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/error-codes',
        'reference/rate-limits',
        'reference/glossary',
      ],
    },
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'reference/api',
    },
  ],
};

export default sidebars;
