//! Pushed Authorization Request storage (RFC 9126).
//!
//! Persists the authorization request parameters pushed to `POST /oauth/par`,
//! referenced by a single-use, short-lived `request_uri`. Tenant-scoped per
//! CLAUDE.md §2 — the caller sets the tenant context for RLS. The `request_uri`
//! reference is generated by the caller (which has a CSPRNG); this model just
//! stores and atomically consumes.

use chrono::{DateTime, Utc};
use sqlx::FromRow;
use uuid::Uuid;

/// RFC 9126 §2.2 `request_uri` URN prefix.
pub const REQUEST_URI_PREFIX: &str = "urn:ietf:params:oauth:request_uri:";

/// A stored pushed authorization request.
#[derive(Debug, Clone, FromRow)]
pub struct PushedAuthRequest {
    /// Opaque single-use reference (the full `urn:…:request_uri:<ref>`).
    pub request_uri: String,
    /// Tenant isolation (RLS-enforced).
    pub tenant_id: Uuid,
    /// Public client_id the request is bound to (must match at `/authorize`).
    pub client_id: String,
    /// Redirect URI (validated at push time).
    pub redirect_uri: String,
    /// Requested scopes (space-delimited).
    pub scope: String,
    /// Opaque CSRF state echoed back to the client.
    pub state: String,
    /// PKCE code challenge.
    pub code_challenge: String,
    /// PKCE method (only S256 supported).
    pub code_challenge_method: String,
    /// OIDC nonce, if provided.
    pub nonce: Option<String>,
    /// OAuth response type (always `code`).
    pub response_type: String,
    /// Expiry (created + ~90s).
    pub expires_at: DateTime<Utc>,
    /// Whether this request has been consumed at `/authorize`.
    pub used: bool,
    /// RFC 9396 `authorization_details` (raw JSONB array), if pushed. Typed and
    /// validated by the OAuth layer; stored opaquely here.
    pub authorization_details: Option<serde_json::Value>,
    /// Creation timestamp.
    pub created_at: DateTime<Utc>,
}

/// Input for storing a pushed authorization request.
#[derive(Debug, Clone)]
pub struct CreatePushedAuthRequest {
    pub request_uri: String,
    pub tenant_id: Uuid,
    pub client_id: String,
    pub redirect_uri: String,
    pub scope: String,
    pub state: String,
    pub code_challenge: String,
    pub code_challenge_method: String,
    pub nonce: Option<String>,
    pub response_type: String,
    pub expires_at: DateTime<Utc>,
    pub authorization_details: Option<serde_json::Value>,
}

impl PushedAuthRequest {
    /// Store a pushed authorization request.
    ///
    /// # Errors
    /// Propagates the underlying `sqlx` error.
    pub async fn create<'e, E>(
        executor: E,
        input: CreatePushedAuthRequest,
    ) -> Result<Self, sqlx::Error>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        sqlx::query_as(
            r"
            INSERT INTO par_requests (
                request_uri, tenant_id, client_id, redirect_uri, scope, state,
                code_challenge, code_challenge_method, nonce, response_type, expires_at,
                authorization_details
            )
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
            RETURNING *
            ",
        )
        .bind(&input.request_uri)
        .bind(input.tenant_id)
        .bind(&input.client_id)
        .bind(&input.redirect_uri)
        .bind(&input.scope)
        .bind(&input.state)
        .bind(&input.code_challenge)
        .bind(&input.code_challenge_method)
        .bind(&input.nonce)
        .bind(&input.response_type)
        .bind(input.expires_at)
        .bind(&input.authorization_details)
        .fetch_one(executor)
        .await
    }

    /// Atomically consume a request_uri: mark it used and return it, only if it
    /// exists, is unused, and is not expired. Returns `Ok(None)` if it cannot be
    /// consumed (missing / already used / expired) — the single-use guarantee
    /// is the `used = FALSE` predicate in the UPDATE (no check-then-use race).
    ///
    /// # Errors
    /// Propagates the underlying `sqlx` error.
    pub async fn consume<'e, E>(
        executor: E,
        tenant_id: Uuid,
        request_uri: &str,
    ) -> Result<Option<Self>, sqlx::Error>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        sqlx::query_as(
            r"
            UPDATE par_requests
            SET used = TRUE
            WHERE request_uri = $1
              AND tenant_id = $2
              AND used = FALSE
              AND expires_at > now()
            RETURNING *
            ",
        )
        .bind(request_uri)
        .bind(tenant_id)
        .fetch_optional(executor)
        .await
    }

    /// Delete expired/used requests past expiry. Returns the count removed.
    ///
    /// # Errors
    /// Propagates the underlying `sqlx` error.
    pub async fn cleanup_expired<'e, E>(executor: E) -> Result<u64, sqlx::Error>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let result = sqlx::query("DELETE FROM par_requests WHERE expires_at < now()")
            .execute(executor)
            .await?;
        Ok(result.rows_affected())
    }
}
