//! # xavyo-db
//!
//! `PostgreSQL` database layer with multi-tenant Row-Level Security (RLS) support
//! for xavyo.
//!
//! ## Features
//!
//! - **Connection Pooling**: Configurable connection pool via `DATABASE_URL`
//! - **Tenant Context**: Automatic tenant context injection for RLS policies
//! - **Migrations**: Versioned SQL migrations with tracking
//! - **Type Safety**: Uses `TenantId` from `xavyo-core` for compile-time safety
//!
//! ## Quick Start
//!
//! ```rust,ignore
//! use xavyo_db::{DbPool, run_migrations, set_tenant_context};
//! use xavyo_core::TenantId;
//!
//! #[tokio::main]
//! async fn main() -> Result<(), xavyo_db::DbError> {
//!     // Connect to database
//!     let pool = DbPool::connect(&std::env::var("DATABASE_URL").unwrap()).await?;
//!
//!     // Run migrations
//!     run_migrations(&pool).await?;
//!
//!     // Set tenant context for RLS
//!     let tenant_id = TenantId::new();
//!     let mut tx = pool.begin().await?;
//!     set_tenant_context(&mut *tx, tenant_id).await?;
//!
//!     // Now all queries are automatically filtered by tenant
//!     Ok(())
//! }
//! ```
//!
//! ## Multi-Tenant Security
//!
//! This library enforces tenant isolation at the database level using `PostgreSQL`
//! Row-Level Security (RLS). When a tenant context is set, all queries on
//! tenant-scoped tables automatically filter by `tenant_id`.
//!
//! If no tenant context is set, queries return zero rows (fail-safe default deny).

pub mod bootstrap;
pub mod error;
pub mod migrations;
pub mod models;
pub mod pool;
pub mod tenant;

pub use error::DbError;
pub use migrations::run_migrations;
pub use models::{
    // Role Mining and Analytics models (F041)
    AccessChange,
    // Enhanced Simulation models (F060)
    AccessItem,
    AccessPatternFilter,
    // Access Request Workflow models (F035)
    AccessRequestFilter,
    // Lifecycle Workflow models (F037)
    AccessSnapshotFilter,
    AccessSnapshotType,
    // Lifecycle Action Execution models (F052/F193)
    ActionExecutionFilter,
    ActionExecutionStatus,
    ActionTriggerType,
    // Self-Service Request Catalog models (F-062)
    AddCartItem,
    // Delegated admin models (F029)
    AdminAction,
    AdminAuditLog,
    AdminPermission,
    AdminResourceType,
    AdminRoleTemplate,
    AdminRoleTemplatePermission,
    // AI Agent models (F089, F110)
    AiAgent,
    AiAgentFilter,
    AiAgentStatus,
    AiAgentType,
    // Risk Scoring models (F039)
    AlertSeverity,
    AlertType,
    // Identity Archetype models (F058)
    AncestryNode,
    ApprovalDetails,
    // Workflow Escalation models (F054)
    ApprovalGroupFilter,
    ApproveGovNhiRequest,
    ArchetypeEventData,
    ArchetypePolicyBinding,
    ArchetypeWithAncestry,
    AssignmentFilter,
    // Parametric Role models (F057)
    AssignmentParameterWithDefinition,
    // Power of Attorney models (F061)
    AssumedSessionFilter,
    // SAML models
    AttributeMap,
    AttributeMapping,
    // Persona archetype configuration types (F063)
    AttributeMappings,
    AttributesPropagatedEventData,
    // Object Lifecycle States models (F052)
    AuditActionType,
    AuditLogFilter,
    // Audit models (F025)
    AuthMethod,
    // WebAuthn models (F032)
    AuthenticatorType,
    // OAuth2 models
    AuthorizationCode,
    AuthorizationCodeBuilder,
    BatchImpactSummary,
    BatchSimulationFilter,
    BatchSimulationResultFilter,
    BatchSimulationType,
    BirthrightChangeDetails,
    BirthrightPolicyFilter,
    BirthrightPolicyStatus,
    BulkAssignmentFailure,
    BulkAssignmentRequest,
    BulkAssignmentResult,
    BulkOperationFilter,
    BulkOperationProgress,
    BulkOperationResult,
    BulkOperationStatus,
    BulkParameterValues,
    // Certification Campaign models (F036)
    CampaignFilter,
    CandidatePromotionStatus,
    CartItemWithDetails,
    CatalogCategory,
    CatalogCategoryFilter,
    CatalogItem,
    CatalogItemFilter,
    CatalogItemType,
    CategorySummary,
    CeremonyType,
    CertCampaignStatus,
    CertDecisionType,
    CertItemFilter,
    CertItemStatus,
    CertItemSummary,
    CertReviewerType,
    CertScopeType,
    CertificateInfo,
    ChangeSpec,
    ClientType,
    // Compliance Reporting models (F042)
    CloneReportTemplate,
    ColumnDefinition,
    ComparisonSummary,
    ComparisonType,
    ComplianceStandard,
    ComputedMapping,
    ConditionMatch,
    ConditionOperator,
    // Outlier Detection models (F059)
    ConfigSnapshot,
    ConsolidationStatus,
    ConsolidationSuggestionFilter,
    ContextSwitchedEventData,
    // Correlation Engine models (F067)
    CorrelationAuditFilter,
    CorrelationCaseFilter,
    CorrelationRuleFilter,
    CreateAccessPattern,
    CreateAccessSnapshot,
    CreateAiAgent,
    CreateAlert,
    CreateApprovalGroup,
    CreateAssignment,
    CreateAuditLogEntry,
    CreateBatchSimulation,
    CreateBatchSimulationResult,
    CreateBirthrightPolicy,
    CreateCatalogCategory,
    CreateCatalogItem,
    CreateCertificationCampaign,
    CreateCertificationDecision,
    CreateCertificationItem,
    CreateConsolidationSuggestion,
    CreateDisposition,
    CreateEscalationEvent,
    CreateEscalationLevel,
    CreateEscalationPolicy,
    CreateEscalationRule,
    CreateExcessivePrivilege,
    // Semi-manual Resources models (F064)
    CreateExternalTicket,
    CreateFailedOperation,
    CreateGovAccessRequest,
    // Governance models (F033)
    CreateGovApplication,
    CreateGovApprovalDecision,
    CreateGovApprovalDelegation,
    CreateGovApprovalStep,
    CreateGovApprovalWorkflow,
    CreateGovAssignment,
    CreateGovBulkStateOperation,
    // Correlation Engine create types (F067)
    CreateGovCorrelationAuditEvent,
    CreateGovCorrelationCandidate,
    CreateGovCorrelationCase,
    CreateGovCorrelationRule,
    // Deputy & Power of Attorney models (F053)
    CreateGovDelegationAudit,
    CreateGovDelegationScope,
    // Orphan Account Detection models (F040)
    CreateGovDetectionRule,
    CreateGovEntitlement,
    CreateGovLifecycleActionExecution,
    CreateGovLifecycleConfig,
    CreateGovLifecycleState,
    CreateGovLifecycleTransition,
    // Meta-role models (F056)
    CreateGovMetaRole,
    CreateGovMetaRoleConflict,
    CreateGovMetaRoleConstraint,
    CreateGovMetaRoleCriteria,
    CreateGovMetaRoleEntitlement,
    CreateGovMetaRoleEvent,
    CreateGovMetaRoleInheritance,
    CreateGovNhiAuditEvent,
    CreateGovNhiCredential,
    CreateGovNhiRequest,
    CreateGovNhiUsageEvent,
    CreateGovOrphanDetection,
    CreateGovPeerGroup,
    CreateGovReconciliationRun,
    CreateGovRemediationLog,
    CreateGovRiskAlert,
    CreateGovRiskEvent,
    CreateGovRiskFactor,
    CreateGovRiskScoreHistory,
    CreateGovRiskThreshold,
    CreateGovRoleEntitlement,
    CreateGovRoleParameter,
    CreateGovScheduledTransition,
    CreateGovServiceAccount,
    // SoD models (F034)
    CreateGovSodExemption,
    CreateGovSodRule,
    CreateGovSodViolation,
    CreateGovStateTransitionAudit,
    CreateGovStateTransitionRequest,
    CreateIdentityArchetype,
    CreateLifecycleAction,
    CreateLifecycleEvent,
    CreateLoginAttempt,
    CreateManualTask,
    CreateManualTaskAuditEvent,
    // MFA models
    CreateMfaAuditLog,
    // Micro-certification models (F055)
    CreateMicroCertEvent,
    CreateMicroCertTrigger,
    CreateMicroCertification,
    CreateMiningJob,
    CreateOutlierAnalysis,
    CreateOutlierResult,
    // Persona Management create types (F063)
    CreatePersona,
    CreatePersonaArchetype,
    CreatePersonaAuditEvent,
    CreatePersonaLink,
    CreatePoaAssumedSession,
    CreatePoaAuditEvent,
    CreatePolicyBinding,
    CreatePolicySimulation,
    CreatePolicySimulationResult,
    CreatePowerOfAttorney,
    CreateReportSchedule,
    CreateReportTemplate,
    CreateRequestCart,
    CreateRoleCandidate,
    CreateRoleMetrics,
    CreateRoleSimulation,
    CreateRoleTemplate,
    CreateSecurityAlert,
    CreateServiceProviderRequest,
    // Session models
    CreateSession,
    CreateSimulationComparison,
    CreateSlaPolicy,
    CreateTicketingConfiguration,
    CreateTotpSecret,
    CreateWebAuthnAuditLog,
    CreateWebAuthnChallenge,
    CreateWebAuthnCredential,
    CredentialInfo,
    CriteriaLogic,
    CriteriaOperator,
    DashboardMetrics,
    DecideMicroCertification,
    // Deputy & Power of Attorney models (F053) - continued
    DelegationActionType,
    DelegationAuditFilter,
    DelegationFilter,
    DelegationStatus,
    DeltaEntry,
    DeltaResults,
    DetectionReason,
    DetectionRuleFilter,
    DetectionRuleType,
    DispositionFilter,
    DispositionSummary,
    EffectivePolicy,
    // Self-service profile models (F027)
    EmailChangeRequest,
    // Auth models
    EmailVerificationToken,
    EmailVerificationTokenBuilder,
    // Passwordless Authentication models (F079) - continued
    EnabledMethods,
    // Risk Enforcement Policy model (F073)
    EnforcementMode,
    EntitlementAction,
    EntitlementChange,
    EntitlementFilter,
    EntitlementInfo,
    EntitlementSnapshot,
    EntitlementUsage,
    EscalationEventFilter,
    EscalationPolicyFilter,
    EscalationPolicyWithLevels,
    EscalationReason,
    EscalationRuleWithLevels,
    EscalationStats,
    EscalationTargetType,
    EvaluationMode,
    ExcessivePrivilegeFilter,
    FactorBreakdown,
    FactorScore,
    FailedLoginAttempt,
    FailedOperationStatus,
    FailedOperationType,
    FailureReason,
    FilterCriteria,
    FilterDefinition,
    FinalFallbackAction,
    FormField,
    GenerateReportRequest,
    GeneratedReportFilter,
    GovAccessPattern,
    GovAccessRequest,
    GovAccessSnapshot,
    GovAppStatus,
    GovAppType,
    GovApplication,
    GovApprovalDecision,
    GovApprovalDelegation,
    GovApprovalGroup,
    GovApprovalStep,
    GovApprovalWorkflow,
    GovApproverType,
    GovAssignmentFilter,
    GovAssignmentStatus,
    GovAssignmentTargetType,
    GovBatchSimulation,
    GovBatchSimulationResult,
    GovBirthrightPolicy,
    GovBulkStateOperation,
    GovCertificationCampaign,
    GovCertificationDecision,
    GovCertificationItem,
    GovConsolidationSuggestion,
    // Correlation Engine types (F067)
    GovCorrelationAuditEvent,
    GovCorrelationCandidate,
    GovCorrelationCase,
    GovCorrelationCaseStatus,
    GovCorrelationEventType,
    GovCorrelationOutcome,
    GovCorrelationRule,
    GovCorrelationThreshold,
    GovCorrelationTrigger,
    GovDecisionType,
    GovDelegationAudit,
    GovDelegationScope,
    GovDetectionRule,
    GovEntitlement,
    GovEntitlementAssignment,
    GovEntitlementStatus,
    GovEscalationEvent,
    GovEscalationLevel,
    GovEscalationPolicy,
    GovEscalationRule,
    GovExcessivePrivilege,
    GovExemptionStatus,
    GovExternalTicket,
    GovFuzzyAlgorithm,
    GovGeneratedReport,
    GovLifecycleAction,
    GovLifecycleActionExecution,
    GovLifecycleConfig,
    GovLifecycleEvent,
    GovLifecycleFailedOperation,
    GovLifecycleState,
    GovLifecycleTransition,
    GovLifecycleTransitionWithStates,
    GovManualProvisioningTask,
    GovManualTaskAuditEvent,
    GovMatchType,
    GovMetaRole,
    GovMetaRoleConflict,
    GovMetaRoleConstraint,
    GovMetaRoleCriteria,
    GovMetaRoleEntitlement,
    GovMetaRoleEvent,
    GovMetaRoleInheritance,
    GovMicroCertEvent,
    GovMicroCertTrigger,
    GovMicroCertification,
    // NHI Lifecycle models (F061)
    GovNhiAuditEvent,
    GovNhiCredential,
    GovNhiRequest,
    GovNhiRiskScore,
    GovNhiUsageEvent,
    GovOrphanDetection,
    GovOutlierAlert,
    GovOutlierAnalysis,
    GovOutlierConfiguration,
    GovOutlierDisposition,
    GovOutlierResult,
    GovParameterAuditEvent,
    GovPeerGroup,
    GovPeerGroupMember,
    // Persona Management models (F063)
    GovPersona,
    GovPersonaArchetype,
    GovPersonaAuditEvent,
    GovPersonaLink,
    GovPersonaSession,
    GovPolicySimulation,
    GovPolicySimulationResult,
    GovReconciliationRun,
    GovRemediationLog,
    GovReportSchedule,
    GovReportTemplate,
    GovRequestStatus,
    GovRiskAlert,
    GovRiskEnforcementPolicy,
    GovRiskEvent,
    GovRiskFactor,
    GovRiskLevel,
    GovRiskScore,
    GovRiskScoreHistory,
    GovRiskThreshold,
    GovRoleAssignmentParameter,
    GovRoleCandidate,
    GovRoleEntitlement,
    GovRoleMetrics,
    GovRoleMiningJob,
    GovRoleParameter,
    GovRoleSimulation,
    GovScheduleStatus,
    GovScheduledTransition,
    GovServiceAccount,
    GovSimulationComparison,
    GovSlaPolicy,
    GovSodExemption,
    GovSodRule,
    GovSodRuleStatus,
    GovSodSeverity,
    GovSodViolation,
    GovStateTransitionAudit,
    GovStateTransitionRequest,
    GovStateTransitionRequestWithStates,
    GovTicketingConfiguration,
    GovViolationStatus,
    IdentityArchetype,
    ImpactSummary,
    ImpactType,
    ImpactTypeCounts,
    InheritanceFilter,
    InheritanceStatus,
    LifecycleActionFilter,
    LifecycleActionType,
    LifecycleConfigFilter,
    LifecycleEventFilter,
    LifecycleEventType,
    LifecycleObjectType,
    LifecyclePolicy,
    LifecycleStateFilter,
    LifecycleTransitionFilter,
    LoginAttempt,
    ManualTaskEventType,
    ManualTaskFilter,
    ManualTaskOperation,
    ManualTaskStatus,
    MetaRoleConflictFilter,
    MetaRoleConflictType,
    MetaRoleEventFilter,
    MetaRoleEventStats,
    MetaRoleEventType,
    MetaRoleFilter,
    MetaRoleStatus,
    MetricsTrendDirection,
    MfaAuditAction,
    MfaAuditLog,
    MfaPolicy,
    MicroCertDecision,
    MicroCertEventFilter,
    MicroCertEventStats,
    MicroCertEventType,
    MicroCertReviewerType,
    MicroCertScopeType,
    MicroCertStatus,
    MicroCertTriggerFilter,
    MicroCertTriggerType,
    MicroCertificationFilter,
    MicroCertificationStats,
    MiningJobFilter,
    MiningJobParameters,
    MiningJobStatus,
    ModifiedEntry,
    NewAuthorizationCode,
    NewOAuth2Client,
    NewOAuthRefreshToken,
    NhiAuditEventFilter,
    NhiAuditEventType,
    NhiCredentialFilter,
    NhiCredentialType,
    NhiEntityType,
    NhiRequestFilter,
    NhiRequestStatus,
    NhiRiskScoreFilter,
    NhiSuspensionReason,
    NhiUsageEventFilter,
    NhiUsageOutcome,
    OAuth2Client,
    OAuth2ClientBuilder,
    OAuthRefreshToken,
    OAuthRefreshTokenBuilder,
    OrphanDetectionFilter,
    OrphanStatus,
    OutlierAlertFilter,
    OutlierAlertSeverity,
    OutlierAlertSummary,
    OutlierAlertType,
    OutlierAnalysisFilter,
    OutlierAnalysisStatus,
    OutlierClassification,
    OutlierDispositionStatus,
    OutlierResultFilter,
    OutlierResultSummary,
    OutlierSeverity,
    OutlierTriggerType,
    OutputFormat,
    ParameterAuditFilter,
    ParameterConstraints,
    ParameterEventType,
    ParameterType,
    PasswordHistory,
    PasswordResetToken,
    PasswordResetTokenBuilder,
    // Passwordless Authentication models (F079)
    PasswordlessPolicy,
    PasswordlessToken,
    PasswordlessTokenType,
    PeerComparison,
    PeerGroupFilter,
    PeerGroupScore,
    PeerGroupType,
    // Correlation Engine per-attribute types (F067)
    PerAttributeScore,
    PerAttributeScores,
    PermissionType,
    // Persona Management types (F063)
    PersonaArchetypeFilter,
    PersonaAttributes,
    PersonaAuditEventFilter,
    PersonaAuditEventType,
    PersonaCreatedEventData,
    PersonaFilter,
    PersonaLinkType,
    PersonaStatus,
    PoaAssumedSession,
    PoaAuditEvent,
    PoaAuditEventFilter,
    PoaEventType,
    PoaFilter,
    PoaStatus,
    PolicyCondition,
    PolicySimulationFilter,
    PolicySimulationResultFilter,
    PolicySimulationType,
    PolicyType,
    PowerOfAttorney,
    PrivilegeFlagStatus,
    PropagateMapping,
    ReconciliationRunFilter,
    ReconciliationStatus,
    RefreshToken,
    RefreshTokenBuilder,
    RejectGovNhiRequest,
    RemediateGovOrphanDetection,
    RemediationAction,
    RemediationLogFilter,
    ReportScheduleFilter,
    ReportStatus,
    ReportTemplateFilter,
    ReportTemplateType,
    RequestCart,
    RequestCartItem,
    RequestabilityRules,
    ResolutionStatus,
    ResolveGovMetaRoleConflict,
    RetryQueueItem,
    RevokeReason,
    RiskAlertFilter,
    RiskAlertSortBy,
    RiskEventFilter,
    RiskFactorCategory,
    RiskFactorFilter,
    RiskLevel,
    RiskScoreFilter,
    RiskScoreSortBy,
    RiskScoreTrend,
    RiskThresholdFilter,
    RoleCandidateFilter,
    RoleEntitlementFilter,
    RoleMetricsFilter,
    RoleParameterFilter,
    RoleSimulationFilter,
    SamlServiceProvider,
    ScenarioType,
    ScheduleFrequency,
    ScheduleStatus,
    ScheduledTransitionFilter,
    ScopeType,
    ScoringWeights,
    SecurityAlert,
    SelectionMode,
    ServiceAccountFilter,
    ServiceAccountStatus,
    Session,
    SessionInfo,
    SetGovAssignmentParameter,
    Severity,
    SeverityCounts,
    SimulationChanges,
    SimulationComparisonFilter,
    SimulationStatus,
    SlaPolicyFilter,
    SnapshotAssignment,
    SnapshotContent,
    SodExemptionFilter,
    SodRuleFilter,
    SodViolationDetails,
    SodViolationFilter,
    SortDefinition,
    TemplateDefinition,
    TemplateStatus,
    // Core tenant model (F095)
    Tenant,
    TenantIdpCertificate,
    // Lockout policy models (F024)
    TenantLockoutPolicy,
    TenantMfaPolicy,
    // Password policy models (F024)
    TenantPasswordPolicy,
    TenantSessionPolicy,
    TenantType,
    TenantWebAuthnPolicy,
    ThresholdAction,
    TicketStatusCategory,
    TicketingConfigFilter,
    TicketingType,
    TransitionAuditFilter,
    TransitionRequestFilter,
    TransitionRequestStatus,
    TrendDirection,
    UpdateAiAgent,
    UpdateApprovalGroup,
    UpdateBirthrightPolicy,
    UpdateCartItem,
    UpdateCatalogCategory,
    UpdateCatalogItem,
    UpdateCertificationCampaign,
    UpdateDisposition,
    UpdateEscalationLevel,
    UpdateEscalationPolicy,
    UpdateEscalationRule,
    UpdateExcessivePrivilegeStatus,
    UpdateGovApplication,
    UpdateGovApprovalWorkflow,
    UpdateGovBulkStateOperation,
    UpdateGovCorrelationRule,
    UpdateGovDetectionRule,
    UpdateGovEntitlement,
    UpdateGovLifecycleConfig,
    UpdateGovLifecycleState,
    UpdateGovLifecycleTransition,
    UpdateGovMetaRole,
    UpdateGovPeerGroupStats,
    UpdateGovReconciliationRun,
    UpdateGovRiskFactor,
    UpdateGovRiskThreshold,
    UpdateGovRoleParameter,
    UpdateGovScheduledTransition,
    UpdateGovServiceAccount,
    UpdateGovSodRule,
    UpdateGovStateTransitionAudit,
    UpdateGovStateTransitionRequest,
    UpdateIdentityArchetype,
    UpdateJobProgress,
    UpdateMicroCertTrigger,
    UpdatePersona,
    UpdatePersonaArchetype,
    UpdateReportSchedule,
    UpdateReportTemplate,
    UpdateRoleTemplate,
    UpdateServiceProviderRequest,
    UpdateSlaPolicy,
    UpdateTicketingConfiguration,
    UploadCertificateRequest,
    UpsertEnforcementPolicy,
    UpsertGovCorrelationThreshold,
    UpsertGovNhiRiskScore,
    UpsertGovRiskScore,
    UpsertLockoutPolicy,
    UpsertOutlierConfiguration,
    UpsertPasswordPolicy,
    UpsertPersonaSession,
    UpsertSessionPolicy,
    UpsertWebAuthnPolicy,
    User,
    UserAdminAssignment,
    UserDevice,
    UserLocation,
    UserRecoveryCode,
    UserRole,
    UserTotpSecret,
    UserVerification,
    UserWebAuthnCredential,
    WebAuthnAuditAction,
    WebAuthnAuditLog,
    WebAuthnAuditLogFilter,
    WebAuthnChallenge,
    WorkItemType,
    WorkflowFilter,
    AUTH_CODE_EXPIRY_MINUTES,
    CHALLENGE_EXPIRY_MINUTES,
    DEFAULT_MAX_CREDENTIALS,
    DEFAULT_REMINDER_THRESHOLD,
    DEFAULT_RETENTION_YEARS,
    DEFAULT_TIMEOUT_SECS,
    MAX_BULK_OPERATION_SIZE,
    MAX_CONSECUTIVE_FAILURES,
    REFRESH_TOKEN_EXPIRY_DAYS,
    SCOPE_WARNING_THRESHOLD,
    SUPPORTED_CONSTRAINT_TYPES,
    SUPPORTED_CRITERIA_FIELDS,
};
pub use pool::{DbPool, DbPoolOptions};
pub use tenant::{clear_tenant_context, get_current_tenant, set_tenant_context, TenantConnection};

// Role Inducements (Construction Pattern) exports (F-063)
pub use models::{
    AttributeMappingType, ConstructionAttributeMapping, ConstructionAttributeMappings,
    ConstructionCondition, ConstructionConditionOperator, ConstructionSourceRole,
    CreateRoleConstruction, CreateRoleInducement, DeprovisioningPolicy, EffectiveConstruction,
    InducedRoleInfo, RoleConstruction, RoleConstructionFilter, RoleConstructionWithDetails,
    RoleInducement, RoleInducementFilter, RoleInducementWithNames, UpdateRoleConstruction,
    UserEffectiveConstruction,
};

// Bootstrap exports (F095)
pub use bootstrap::{
    run_bootstrap, BootstrapError, BootstrapResult, CLI_OAUTH_CLIENT_ID, CLI_OAUTH_CLIENT_NAME,
    CLI_OAUTH_CLIENT_UUID, CLI_OAUTH_GRANT_TYPES, CLI_OAUTH_SCOPES, SYSTEM_TENANT_ID,
    SYSTEM_TENANT_NAME, SYSTEM_TENANT_SLUG,
};

// Bulk Action Engine exports (F-064)
pub use models::{
    CreateGovBulkAction, GovBulkAction, GovBulkActionFilter, GovBulkActionProgress,
    GovBulkActionResultItem, GovBulkActionStatus, GovBulkActionType, UpdateGovBulkAction,
    MAX_BULK_ACTION_SIZE, MIN_JUSTIFICATION_LENGTH,
};
