#!/usr/bin/env bash
# Generate JWT keys and .env with dev-safe defaults for local development.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
KEYS_DIR="$PROJECT_ROOT/docker/keys"
ENV_FILE="$PROJECT_ROOT/.env"

echo "[setup-dev-env] Generating JWT keys..."
bash "$PROJECT_ROOT/docker/generate-keys.sh"

PRIVATE_KEY="$(cat "$KEYS_DIR/jwt_private.pem")"
PUBLIC_KEY="$(cat "$KEYS_DIR/jwt_public.pem")"
GOV_KEY="$(openssl rand -base64 32)"
POSTGRES_PORT="${POSTGRES_PORT:-5434}"

python3 - "$ENV_FILE" "$POSTGRES_PORT" "$GOV_KEY" "$KEYS_DIR" <<'PY'
import sys
from pathlib import Path

env_path, postgres_port, gov_key, keys_dir = sys.argv[1:5]
private = Path(keys_dir, "jwt_private.pem").read_text()
public = Path(keys_dir, "jwt_public.pem").read_text()

content = f"""# Generated by scripts/setup-dev-env.sh — safe for local development only
APP_ENV=development
DATABASE_URL=postgres://xavyo:xavyo_test_password@localhost:{postgres_port}/xavyo_test

JWT_PRIVATE_KEY={private!r}
JWT_PUBLIC_KEY={public!r}
JWT_KEY_ID=primary
ISSUER_URL=http://localhost:8080
FRONTEND_URL=http://localhost:3000
HOST=0.0.0.0
PORT=8080
RUST_LOG=info,xavyo=debug

CORS_ORIGINS=http://localhost:3000,http://localhost:8080

EMAIL_SMTP_HOST=localhost
EMAIL_SMTP_PORT=1025
EMAIL_SMTP_TLS=false
EMAIL_FROM_ADDRESS=noreply@xavyo.local
EMAIL_FROM_NAME=xavyo

ADMIN_EMAIL=admin@xavyo.local
ADMIN_PASSWORD=Admin@1234

XAVYO_SIEM_ENCRYPTION_KEY={gov_key}
XAVYO_TICKETING_ENCRYPTION_KEY={gov_key}
"""
Path(env_path).write_text(content)
PY

echo "[setup-dev-env] Wrote $ENV_FILE"
echo "[setup-dev-env] Admin: admin@xavyo.local / Admin@1234"
echo "[setup-dev-env] Tenant: 00000000-0000-0000-0000-000000000001"
